// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Taffy
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "ctaffy";





        /// <summary>
        ///  Create a TaffyTree instance
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_New", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyNativeTree* TaffyTree_New();

        /// <summary>
        ///  Free a TaffyTree instance
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_Free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_Free(TaffyNativeTree* raw_tree);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_ComputeLayout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_ComputeLayout(TaffyNativeTree* raw_tree, TaffyNodeId node_id, float available_width, float available_height);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_PrintTree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_PrintTree(TaffyNativeTree* raw_tree, TaffyNodeId node_id);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_NewNode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyNodeIdResult TaffyTree_NewNode(TaffyNativeTree* raw_tree);

        /// <summary>
        ///  Remove and Free a Node within a TaffyTree
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_RemoveNode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_RemoveNode(TaffyNativeTree* raw_tree, TaffyNodeId node_id);

        /// <summary>
        ///  Remove and Free a Node within a TaffyTree
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_AppendChild", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_AppendChild(TaffyNativeTree* raw_tree, TaffyNodeId parent_node_id, TaffyNodeId child_node_id);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_GetStyleMut", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyStyleMutRefResult TaffyTree_GetStyleMut(TaffyNativeTree* raw_tree, TaffyNodeId node_id);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_SetNodeContext", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_SetNodeContext(TaffyNativeTree* raw_tree, TaffyNodeId node_id, delegate* unmanaged[Cdecl]<TaffyMeasureMode, float, TaffyMeasureMode, float, void*, TaffySize> measure_function, void* context);

        /// <summary>
        ///  Create a new Node in the TaffyTree. Returns a NodeId handle to the node.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_GetLayout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyLayoutResult TaffyTree_GetLayout(TaffyNativeTree* raw_tree, TaffyNodeId node_id);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAspectRatio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetAspectRatio(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAspectRatio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAspectRatio(TaffyStyle* raw_style, float value);

        /// <summary>
        ///  Function to set all the value of margin
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMargin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMargin(TaffyStyle* raw_style, TaffyEdge edge, TaffyDimension value);

        /// <summary>
        ///  Get grid item's column placement
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridColumn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridPlacement TaffyStyle_GetGridColumn(TaffyStyle* raw_style);

        /// <summary>
        ///  Set grid item's column placement
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridColumn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridColumn(TaffyStyle* raw_style, TaffyGridPlacement placement);

        /// <summary>
        ///  Get grid item's row placement
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridRow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridPlacement TaffyStyle_GetGridRow(TaffyStyle* raw_style);

        /// <summary>
        ///  Set grid item's row placement
        /// </summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridRow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridRow(TaffyStyle* raw_style, TaffyGridPlacement placement);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetDisplay", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDisplay TaffyStyle_GetDisplay(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetDisplay", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetDisplay(TaffyStyle* _raw_style, TaffyDisplay _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPosition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyPosition TaffyStyle_GetPosition(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPosition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPosition(TaffyStyle* _raw_style, TaffyPosition _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetOverflowX", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyOverflow TaffyStyle_GetOverflowX(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetOverflowX", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetOverflowX(TaffyStyle* _raw_style, TaffyOverflow _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetOverflowY", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyOverflow TaffyStyle_GetOverflowY(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetOverflowY", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetOverflowY(TaffyStyle* _raw_style, TaffyOverflow _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignContent(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignItems(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignSelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignSelf(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifyContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifyContent(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifyItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifyItems(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifySelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifySelf(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignContent(TaffyStyle* _raw_style, TaffyAlignContent _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignItems(TaffyStyle* _raw_style, TaffyAlignItems _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignSelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignSelf(TaffyStyle* _raw_style, TaffyAlignItems _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifyContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifyContent(TaffyStyle* _raw_style, TaffyAlignContent _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifyItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifyItems(TaffyStyle* _raw_style, TaffyAlignItems _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifySelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifySelf(TaffyStyle* _raw_style, TaffyAlignItems _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexDirection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyFlexDirection TaffyStyle_GetFlexDirection(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexDirection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexDirection(TaffyStyle* _raw_style, TaffyFlexDirection _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexWrap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyFlexWrap TaffyStyle_GetFlexWrap(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexWrap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexWrap(TaffyStyle* _raw_style, TaffyFlexWrap _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridAutoFlow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridAutoFlow TaffyStyle_GetGridAutoFlow(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridAutoFlow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridAutoFlow(TaffyStyle* _raw_style, TaffyGridAutoFlow _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetWidth(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetWidth(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetHeight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetHeight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMinWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMinWidth(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMinWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMinWidth(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMinHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMinHeight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMinHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMinHeight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMaxWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMaxWidth(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMaxWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMaxWidth(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMaxHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMaxHeight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMaxHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMaxHeight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetTop(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetTop(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetBottom(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetBottom(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetLeft(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetLeft(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetRight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetRight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginTop(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginTop(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginBottom(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginBottom(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginLeft(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginLeft(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginRight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginRight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingTop(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingTop(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingBottom(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingBottom(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingLeft(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingLeft(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingRight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingRight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderTop(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderTop(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderBottom(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderBottom(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderLeft(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderLeft(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderRight(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderRight(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetColumnGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetColumnGap(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetColumnGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetColumnGap(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetRowGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetRowGap(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetRowGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetRowGap(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetScrollbarWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetScrollbarWidth(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetScrollbarWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetScrollbarWidth(TaffyStyle* _raw_style, float _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexBasis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetFlexBasis(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexBasis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexBasis(TaffyStyle* _raw_style, float _value, TaffyUnit _unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexGrow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetFlexGrow(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexGrow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexGrow(TaffyStyle* _raw_style, float _value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexShrink", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetFlexShrink(TaffyStyle* _raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexShrink", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexShrink(TaffyStyle* _raw_style, float _value);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyStyle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffySize
    {
        public float width;
        public float height;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyLayout
    {
        public float x;
        public float y;
        public float width;
        public float height;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyDimension
    {
        /// <summary>
        ///  The value. If the unit is variant that doesn't require a value (e.g. Auto) then the value is ignored.
        /// </summary>
        public float value;
        public TaffyUnit unit;
    }

    /// <summary>
    ///  For all fields, zero represents not set
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyGridPlacement
    {
        public short start;
        public short end;
        public ushort span;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyNativeTree
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyNodeId
    {
        public ulong Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyNodeIdResult
    {
        public TaffyReturnCode return_code;
        public TaffyNodeId value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyStyleMutRefResult
    {
        public TaffyReturnCode return_code;
        public TaffyStyle* value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TaffyLayoutResult
    {
        public TaffyReturnCode return_code;
        public TaffyLayout value;
    }


    public enum TaffyReturnCode : uint
    {
        /// <summary>
        ///  Operation suceeded
        /// </summary>
        Ok,
        /// <summary>
        ///  The style pointer passed was null
        /// </summary>
        NullStylePointer,
        /// <summary>
        ///  The tree pointer passed was null
        /// </summary>
        NullTreePointer,
        /// <summary>
        ///  The node referenced by the node id passed does not exist
        /// </summary>
        InvalidNodeId,
        /// <summary>
        ///  An enum value was specified that was outside the range of valid value for this enum
        /// </summary>
        InvalidEnumValue,
        /// <summary>
        ///  A Points unit was specified but is not valid in this context
        /// </summary>
        InvalidNone,
        /// <summary>
        ///  A Points unit was specified but is not valid in this context
        /// </summary>
        InvalidPoints,
        /// <summary>
        ///  A Percent unit was specified but is not valid in this context
        /// </summary>
        InvalidPercent,
        /// <summary>
        ///  A MinContent unit was specified but is not valid in this context
        /// </summary>
        InvalidMinContent,
        /// <summary>
        ///  A MaxContent unit was specified but is not valid in this context
        /// </summary>
        InvalidMaxContent,
        /// <summary>
        ///  A FitContentPx unit was specified but is not valid in this context
        /// </summary>
        InvalidFitContentPx,
        /// <summary>
        ///  A FitContentPercent unit was specified but is not valid in this context
        /// </summary>
        InvalidFitContentPercent,
        /// <summary>
        ///  An Auto unit was specified but is not valid in this context
        /// </summary>
        InvalidAuto,
        /// <summary>
        ///  An Fr unit was specified but is not valid in this context
        /// </summary>
        InvalidFr,
        /// <summary>
        ///  A NaN value was specified but is not valid in this context
        /// </summary>
        UnexpectedNaN,
        /// <summary>
        ///  A infinite value was specified but is not valid in this context
        /// </summary>
        UnexpectedInfinity,
        /// <summary>
        ///  A negative value was specified but is not valid in this context
        /// </summary>
        UnexpectedNegative,
    }

    public enum TaffyEdge : uint
    {
        /// <summary>
        ///  The top edge of the box
        /// </summary>
        Top,
        /// <summary>
        ///  The bottom edge of the box
        /// </summary>
        Bottom,
        /// <summary>
        ///  The left edge of the box
        /// </summary>
        Left,
        /// <summary>
        ///  The right edge of the box
        /// </summary>
        Right,
        /// <summary>
        ///  Both the top and bottom edges of the box
        /// </summary>
        Vertical,
        /// <summary>
        ///  Both the left and right edges of the box
        /// </summary>
        Horizontal,
        /// <summary>
        ///  All four edges of the box
        /// </summary>
        All,
    }

    public enum TaffyUnit : uint
    {
        /// <summary>
        ///  A none value (used to unset optional fields)
        /// </summary>
        None,
        /// <summary>
        ///  Fixed Length (pixel) value
        /// </summary>
        Length,
        /// <summary>
        ///  Percentage value
        /// </summary>
        Percent,
        /// <summary>
        ///  Min-content size
        /// </summary>
        MinContent,
        /// <summary>
        ///  Max-content size
        /// </summary>
        MaxContent,
        /// <summary>
        ///  fit-content() function with a pixel limit
        /// </summary>
        FitContentPx,
        /// <summary>
        ///  fit-content() function with a percentage limit
        /// </summary>
        FitContentPercent,
        /// <summary>
        ///  Automatic values
        /// </summary>
        Auto,
        /// <summary>
        ///  fr unit
        /// </summary>
        Fr,
    }

    public enum TaffyMeasureMode : uint
    {
        /// <summary>
        ///  A none value (used to unset optional fields)
        /// </summary>
        Exact,
        /// <summary>
        ///  Fixed Length (pixel) value
        /// </summary>
        FitContent,
        /// <summary>
        ///  Percentage value
        /// </summary>
        MinContent,
        /// <summary>
        ///  Min-content size
        /// </summary>
        MaxContent,
    }

    /// <summary>
    ///  Sets the layout used for the children of this node
    ///
    ///  The default values depends on on which feature flags are enabled. The order of precedence is: Flex, Grid, Block, None.
    /// </summary>
    public enum TaffyDisplay : uint
    {
        /// <summary>
        ///  The children will follow the block layout algorithm
        /// </summary>
        Block,
        /// <summary>
        ///  The children will follow the flexbox layout algorithm
        /// </summary>
        Flex,
        /// <summary>
        ///  The children will follow the CSS Grid layout algorithm
        /// </summary>
        Grid,
        /// <summary>
        ///  The children will not be laid out, and will follow absolute positioning
        /// </summary>
        None,
    }

    /// <summary>
    ///  The positioning strategy for this item.
    ///
    ///  This controls both how the origin is determined for the [`Style::position`] field,
    ///  and whether or not the item will be controlled by flexbox's layout algorithm.
    ///
    ///  WARNING: this enum follows the behavior of [CSS's `position` property](https://developer.mozilla.org/en-US/docs/Web/CSS/position),
    ///  which can be unintuitive.
    ///
    ///  [`Position::Relative`] is the default value, in contrast to the default behavior in CSS.
    /// </summary>
    public enum TaffyPosition : uint
    {
        /// <summary>
        ///  The offset is computed relative to the final position given by the layout algorithm.
        ///  Offsets do not affect the position of any other items; they are effectively a correction factor applied at the end.
        /// </summary>
        Relative,
        /// <summary>
        ///  The offset is computed relative to this item's closest positioned ancestor, if any.
        ///  Otherwise, it is placed relative to the origin.
        ///  No space is created for the item in the page layout, and its size will not be altered.
        ///
        ///  WARNING: to opt-out of layouting entirely, you must use [`Display::None`] instead on your [`Style`] object.
        /// </summary>
        Absolute,
    }

    /// <summary>
    ///  How children overflowing their container should affect layout
    ///
    ///  In CSS the primary effect of this property is to control whether contents of a parent container that overflow that container should
    ///  be displayed anyway, be clipped, or trigger the container to become a scroll container. However it also has secondary effects on layout,
    ///  the main ones being:
    ///
    ///    - The automatic minimum size Flexbox/CSS Grid items with non-`Visible` overflow is `0` rather than being content based
    ///    - `Overflow::Scroll` nodes have space in the layout reserved for a scrollbar (width controlled by the `scrollbar_width` property)
    ///
    ///  In Taffy, we only implement the layout related secondary effects as we are not concerned with drawing/painting. The amount of space reserved for
    ///  a scrollbar is controlled by the `scrollbar_width` property. If this is `0` then `Scroll` behaves identically to `Hidden`.
    ///
    ///  &lt;https://developer.mozilla.org/en-US/docs/Web/CSS/overflow&gt;
    /// </summary>
    public enum TaffyOverflow : uint
    {
        /// <summary>
        ///  The automatic minimum size of this node as a flexbox/grid item should be based on the size of it's content.
        /// </summary>
        Visible,
        /// <summary>
        ///  The automatic minimum size of this node as a flexbox/grid item should be based on the size of its content.
        ///  Content that overflows this node should *not* contribute to the scroll region of its parent.
        /// </summary>
        Clip,
        /// <summary>
        ///  The automatic minimum size of this node as a flexbox/grid item should be `0`.
        /// </summary>
        Hidden,
        /// <summary>
        ///  The automatic minimum size of this node as a flexbox/grid item should be `0`. Additionally, space should be reserved
        ///  for a scrollbar. The amount of space reserved is controlled by the `scrollbar_width` property.
        /// </summary>
        Scroll,
    }

    /// <summary>
    ///  Used to control how child nodes are aligned.
    ///  For Flexbox it controls alignment in the cross axis
    ///  For Grid it controls alignment in the block axis
    ///
    ///  [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)
    /// </summary>
    public enum TaffyAlignItems : uint
    {
        /// <summary>
        ///  Items are aligned according to their algorithm-specific default value
        ///  This is equivalent to not setting a value in CSS
        /// </summary>
        Normal,
        /// <summary>
        ///  Items are packed toward the start of the axis
        /// </summary>
        Start,
        /// <summary>
        ///  Items are packed toward the end of the axis
        /// </summary>
        End,
        /// <summary>
        ///  Items are packed towards the flex-relative start of the axis.
        ///
        ///  For flex containers with flex_direction RowReverse or ColumnReverse this is equivalent
        ///  to End. In all other cases it is equivalent to Start.
        /// </summary>
        FlexStart,
        /// <summary>
        ///  Items are packed towards the flex-relative end of the axis.
        ///
        ///  For flex containers with flex_direction RowReverse or ColumnReverse this is equivalent
        ///  to Start. In all other cases it is equivalent to End.
        /// </summary>
        FlexEnd,
        /// <summary>
        ///  Items are packed along the center of the cross axis
        /// </summary>
        Center,
        /// <summary>
        ///  Items are aligned such as their baselines align
        /// </summary>
        Baseline,
        /// <summary>
        ///  Stretch to fill the container
        /// </summary>
        Stretch,
    }

    /// <summary>
    ///  Sets the distribution of space between and around content items
    ///  For Flexbox it controls alignment in the cross axis
    ///  For Grid it controls alignment in the block axis
    ///
    ///  [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-content)
    /// </summary>
    public enum TaffyAlignContent : uint
    {
        /// <summary>
        ///  Items are aligned according to their algorithm-specific default value
        ///  This is equivalent to not setting a value in CSS
        /// </summary>
        Normal,
        /// <summary>
        ///  Items are packed toward the start of the axis
        /// </summary>
        Start,
        /// <summary>
        ///  Items are packed toward the end of the axis
        /// </summary>
        End,
        /// <summary>
        ///  Items are packed towards the flex-relative start of the axis.
        ///
        ///  For flex containers with flex_direction RowReverse or ColumnReverse this is equivalent
        ///  to End. In all other cases it is equivalent to Start.
        /// </summary>
        FlexStart,
        /// <summary>
        ///  Items are packed towards the flex-relative end of the axis.
        ///
        ///  For flex containers with flex_direction RowReverse or ColumnReverse this is equivalent
        ///  to Start. In all other cases it is equivalent to End.
        /// </summary>
        FlexEnd,
        /// <summary>
        ///  Items are centered around the middle of the axis
        /// </summary>
        Center,
        /// <summary>
        ///  Items are stretched to fill the container
        /// </summary>
        Stretch,
        /// <summary>
        ///  The first and last items are aligned flush with the edges of the container (no gap)
        ///  The gap between items is distributed evenly.
        /// </summary>
        SpaceBetween,
        /// <summary>
        ///  The gap between the first and last items is exactly THE SAME as the gap between items.
        ///  The gaps are distributed evenly
        /// </summary>
        SpaceEvenly,
        /// <summary>
        ///  The gap between the first and last items is exactly HALF the gap between items.
        ///  The gaps are distributed evenly in proportion to these ratios.
        /// </summary>
        SpaceAround,
    }

    /// <summary>
    ///  Controls whether flex items are forced onto one line or can wrap onto multiple lines.
    ///
    ///  Defaults to [`FlexWrap::NoWrap`]
    ///
    ///  [Specification](https://www.w3.org/TR/css-flexbox-1/#flex-wrap-property)
    /// </summary>
    public enum TaffyFlexWrap : uint
    {
        /// <summary>
        ///  Items will not wrap and stay on a single line
        /// </summary>
        NoWrap,
        /// <summary>
        ///  Items will wrap according to this item's [`FlexDirection`]
        /// </summary>
        Wrap,
        /// <summary>
        ///  Items will wrap in the opposite direction to this item's [`FlexDirection`]
        /// </summary>
        WrapReverse,
    }

    /// <summary>
    ///  The direction of the flexbox layout main axis.
    ///
    ///  There are always two perpendicular layout axes: main (or primary) and cross (or secondary).
    ///  Adding items will cause them to be positioned adjacent to each other along the main axis.
    ///  By varying this value throughout your tree, you can create complex axis-aligned layouts.
    ///
    ///  Items are always aligned relative to the cross axis, and justified relative to the main axis.
    ///
    ///  The default behavior is [`FlexDirection::Row`].
    ///
    ///  [Specification](https://www.w3.org/TR/css-flexbox-1/#flex-direction-property)
    /// </summary>
    public enum TaffyFlexDirection : uint
    {
        /// <summary>
        ///  Defines +x as the main axis
        ///
        ///  Items will be added from left to right in a row.
        /// </summary>
        Row,
        /// <summary>
        ///  Defines +y as the main axis
        ///
        ///  Items will be added from top to bottom in a column.
        /// </summary>
        Column,
        /// <summary>
        ///  Defines -x as the main axis
        ///
        ///  Items will be added from right to left in a row.
        /// </summary>
        RowReverse,
        /// <summary>
        ///  Defines -y as the main axis
        ///
        ///  Items will be added from bottom to top in a column.
        /// </summary>
        ColumnReverse,
    }

    /// <summary>
    ///  Controls whether grid items are placed row-wise or column-wise. And whether the sparse or dense packing algorithm is used.
    ///
    ///  The "dense" packing algorithm attempts to fill in holes earlier in the grid, if smaller items come up later.
    ///  This may cause items to appear out-of-order, when doing so would fill in holes left by larger items.
    ///
    ///  Defaults to [`GridAutoFlow::Row`]
    ///
    ///  [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow)
    /// </summary>
    public enum TaffyGridAutoFlow : uint
    {
        /// <summary>
        ///  Items are placed by filling each row in turn, adding new rows as necessary
        /// </summary>
        Row,
        /// <summary>
        ///  Items are placed by filling each column in turn, adding new columns as necessary.
        /// </summary>
        Column,
        /// <summary>
        ///  Combines `Row` with the dense packing algorithm.
        /// </summary>
        RowDense,
        /// <summary>
        ///  Combines `Column` with the dense packing algorithm.
        /// </summary>
        ColumnDense,
    }


}
