// This file is processed by csbindgen (via build.rs) to generate C# P/Invoke bindings.
// It provides explicit `extern "C"` function signatures for functions generated by Rust
// macros in bindings/c/src/style.rs, which csbindgen cannot expand automatically.

use ctaffy::{TaffyAlignContent, TaffyAlignItems, TaffyDimension, TaffyDisplay, TaffyFlexDirection, TaffyFlexWrap, TaffyGridAutoFlow, TaffyOverflow, TaffyPosition, TaffyReturnCode, TaffyStyle, TaffyUnit};

// Display
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetDisplay(_raw_style: *const TaffyStyle) -> TaffyDisplay { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetDisplay(_raw_style: *mut TaffyStyle, _value: TaffyDisplay) -> TaffyReturnCode { loop {} }

// Position
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetPosition(_raw_style: *const TaffyStyle) -> TaffyPosition { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetPosition(_raw_style: *mut TaffyStyle, _value: TaffyPosition) -> TaffyReturnCode { loop {} }

// Overflow
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetOverflowX(_raw_style: *const TaffyStyle) -> TaffyOverflow { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetOverflowX(_raw_style: *mut TaffyStyle, _value: TaffyOverflow) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetOverflowY(_raw_style: *const TaffyStyle) -> TaffyOverflow { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetOverflowY(_raw_style: *mut TaffyStyle, _value: TaffyOverflow) -> TaffyReturnCode { loop {} }

// Alignment (optional enums returned as i32, 0 = unset/Normal)
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetAlignContent(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetAlignItems(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetAlignSelf(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetJustifyContent(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetJustifyItems(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetJustifySelf(_raw_style: *const TaffyStyle) -> i32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetAlignContent(_raw_style: *mut TaffyStyle, _value: TaffyAlignContent) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetAlignItems(_raw_style: *mut TaffyStyle, _value: TaffyAlignItems) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetAlignSelf(_raw_style: *mut TaffyStyle, _value: TaffyAlignItems) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetJustifyContent(_raw_style: *mut TaffyStyle, _value: TaffyAlignContent) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetJustifyItems(_raw_style: *mut TaffyStyle, _value: TaffyAlignItems) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetJustifySelf(_raw_style: *mut TaffyStyle, _value: TaffyAlignItems) -> TaffyReturnCode { loop {} }

// FlexDirection / FlexWrap
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetFlexDirection(_raw_style: *const TaffyStyle) -> TaffyFlexDirection { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetFlexDirection(_raw_style: *mut TaffyStyle, _value: TaffyFlexDirection) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetFlexWrap(_raw_style: *const TaffyStyle) -> TaffyFlexWrap { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetFlexWrap(_raw_style: *mut TaffyStyle, _value: TaffyFlexWrap) -> TaffyReturnCode { loop {} }

// GridAutoFlow
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetGridAutoFlow(_raw_style: *const TaffyStyle) -> TaffyGridAutoFlow { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetGridAutoFlow(_raw_style: *mut TaffyStyle, _value: TaffyGridAutoFlow) -> TaffyReturnCode { loop {} }

// Size
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetWidth(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetWidth(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetHeight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetHeight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// MinSize
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMinWidth(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMinWidth(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMinHeight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMinHeight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// MaxSize
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMaxWidth(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMaxWidth(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMaxHeight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMaxHeight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Inset
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetInsetTop(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetInsetTop(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetInsetBottom(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetInsetBottom(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetInsetLeft(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetInsetLeft(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetInsetRight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetInsetRight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Margin
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMarginTop(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMarginTop(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMarginBottom(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMarginBottom(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMarginLeft(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMarginLeft(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetMarginRight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetMarginRight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Padding
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetPaddingTop(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetPaddingTop(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetPaddingBottom(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetPaddingBottom(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetPaddingLeft(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetPaddingLeft(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetPaddingRight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetPaddingRight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Border
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetBorderTop(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetBorderTop(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetBorderBottom(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetBorderBottom(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetBorderLeft(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetBorderLeft(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetBorderRight(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetBorderRight(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Gap
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetColumnGap(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetColumnGap(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetRowGap(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetRowGap(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }

// Scrollbar
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetScrollbarWidth(_raw_style: *const TaffyStyle) -> f32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetScrollbarWidth(_raw_style: *mut TaffyStyle, _value: f32) -> TaffyReturnCode { loop {} }

// Flex
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetFlexBasis(_raw_style: *const TaffyStyle) -> TaffyDimension { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetFlexBasis(_raw_style: *mut TaffyStyle, _value: f32, _unit: TaffyUnit) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetFlexGrow(_raw_style: *const TaffyStyle) -> f32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetFlexGrow(_raw_style: *mut TaffyStyle, _value: f32) -> TaffyReturnCode { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_GetFlexShrink(_raw_style: *const TaffyStyle) -> f32 { loop {} }
#[no_mangle] pub unsafe extern "C" fn TaffyStyle_SetFlexShrink(_raw_style: *mut TaffyStyle, _value: f32) -> TaffyReturnCode { loop {} }
